// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmjEy-vJbIHPeGvwgOB6MiRNz1PY4VwUE',
    appId: '1:1019359089325:web:7da0e21ab29debd1b9ec24',
    messagingSenderId: '1019359089325',
    projectId: 'weight-app-8df93',
    authDomain: 'weight-app-8df93.firebaseapp.com',
    storageBucket: 'weight-app-8df93.appspot.com',
    measurementId: 'G-86QKT7RDBJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqtcNs9s5ZFG6cPhvgJc_kJYOyeHNhwxA',
    appId: '1:1019359089325:android:7719f0429445473fb9ec24',
    messagingSenderId: '1019359089325',
    projectId: 'weight-app-8df93',
    storageBucket: 'weight-app-8df93.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1rHM2j2K-jSA0KEQFarvxFzZ7oz24KwY',
    appId: '1:1019359089325:ios:15a42b8eb35abdb7b9ec24',
    messagingSenderId: '1019359089325',
    projectId: 'weight-app-8df93',
    storageBucket: 'weight-app-8df93.appspot.com',
    iosClientId: '1019359089325-udbf5ok61lm2s6ldbdcbhpf6t0p9bm0c.apps.googleusercontent.com',
    iosBundleId: 'com.example.weightApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1rHM2j2K-jSA0KEQFarvxFzZ7oz24KwY',
    appId: '1:1019359089325:ios:15a42b8eb35abdb7b9ec24',
    messagingSenderId: '1019359089325',
    projectId: 'weight-app-8df93',
    storageBucket: 'weight-app-8df93.appspot.com',
    iosClientId: '1019359089325-udbf5ok61lm2s6ldbdcbhpf6t0p9bm0c.apps.googleusercontent.com',
    iosBundleId: 'com.example.weightApp',
  );
}
